### ISSUE TITLE
Does not build with generic-lens 2.0.0.0

### ISSUE THREAD

**Issue by AlistairB** [i-am-tom/higgledy#23]
Fails with:

```
src/Data/Generic/HKD/Named.hs:31:1: error:
    Could not load module ‘Data.GenericLens.Internal’
    It is a member of the hidden package ‘generic-lens-core-2.0.0.0’.
    Perhaps you need to add ‘generic-lens-core’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘generic-lens-1.1.0.0’.
    Perhaps you need to add ‘generic-lens’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
31 | import Data.GenericLens.Internal (GUpcast (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

when including `generic-lens-core` it fails with:

```
src/Data/Generic/HKD/Named.hs:31:35: error:
    Module ‘Data.GenericLens.Internal’ does not export ‘GUpcast(..)’
   |
31 | import Data.GenericLens.Internal (GUpcast (..))
   |
```

It seems `GUpcast` has moved to https://hackage.haskell.org/package/generic-lens-core-2.0.0.0/docs/Data-Generics-Product-Internal-Subtype.html , however, it is no longer an exported module. When exporting it it builds.

I also had to import `HList` from `Data.Generics.Product.Internal.HList`.

I'll put up a PR with these changes, but I guess generic-lens would need to be updated to expose `GUpcast` again?

**Comment by i-am-tom** [comment]
Paging @kcsongor, would you mind exposing GUpcast for us? :heart:

**Comment by kcsongor** [comment]
Uh oh! Looks like I wasn't careful enough when reorganising the internals. I have a bit of a backlog for an upcoming release, I'll make sure to include this too when I finally get to it!

**Comment by i-am-tom** [comment]
Small update to this @AlistairB (sorry for the extreme wait), there's a PR here https://github.com/kcsongor/generic-lens/pull/127 that should fix this problem!
