### PR TITLE
Update to generic lens 2.1.0.0

### LINKED ISSUE #23: Does not build with generic-lens 2.0.0.0
Fails with:

```
src/Data/Generic/HKD/Named.hs:31:1: error:
    Could not load module ‘Data.GenericLens.Internal’
    It is a member of the hidden package ‘generic-lens-core-2.0.0.0’.
    Perhaps you need to add ‘generic-lens-core’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘generic-lens-1.1.0.0’.
    Perhaps you need to add ‘generic-lens’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
31 | import Data.GenericLens.Internal (GUpcast (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

when including `generic-lens-core` it fails with:

```
src/Data/Generic/HKD/Named.hs:31:35: error:
    Module ‘Data.GenericLens.Internal’ does not export ‘GUpcast(..)’
   |
31 | import Data.GenericLens.Internal (GUpcast (..))
   |
```

It seems `GUpcast` has moved to https://hackage.haskell.org/package/generic-lens-core-2.0.0.0/docs/Data-Generics-Product-Internal-Subtype.html , however, it is no longer an exported module. When exporting it it builds.

I also had to import `HList` from `Data.Generics.Product.Internal.HList`.

I'll put up a PR with these changes, but I guess generic-lens would need to be updated to expose `GUpcast` again?

### PR DESCRIPTION
**Pull request by AlistairB**
Closes #23

Generic lens 2.1.0.0 exposes `GUpcast` now :tada: 

I was a bit unsure on whether to do `^>= 2.1` vs `>= 2.1 && < 3.0` for generic lens. I figure 2.* versions are likely to work ok so went with the latter.

### CODE REVIEW

**Comment by i-am-tom** [comment]
Ah, you absolute star! I was going to do this tomorrow :D Thanks so much, I'll push a release now!
